name: Sudoku
options:
  bundleIdPrefix: com.maxlestage
  deploymentTarget:
    iOS: "16.0"
targets:
  Sudoku:
    type: application
    platform: iOS
    sources: [Sudoku]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.maxlestage.sudoku
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "4"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Sudoku/Info.plist
      properties:
        CFBundleDisplayName: Sudoku
        CFBundleIconName: AppIcon
        CFBundleLocalizations: [fr, es, en]
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
